version: "3.8"
services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo1_data:/data/db
      - ./mongo-keyfile:/data/replica.key
    networks:
      - mongo-cluster
    command:
      [
        "--replSet",
        "replica0",
        "--bind_ip_all",
        "--keyFile",
        "/data/replica.key",
      ]

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo2_data:/data/db
      - ./mongo-keyfile:/data/replica.key
    networks:
      - mongo-cluster
    command:
      [
        "--replSet",
        "replica0",
        "--bind_ip_all",
        "--keyFile",
        "/data/replica.key",
      ]

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo3_data:/data/db
      - ./mongo-keyfile:/data/replica.key
    networks:
      - mongo-cluster
    command:
      [
        "--replSet",
        "replica0",
        "--bind_ip_all",
        "--keyFile",
        "/data/replica.key",
      ]

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
networks:
  mongo-cluster:
